#ifndef SHTC3_H
#define SHTC3_H

#ifndef F_CPU
#define F_CPU 16000000UL // ATMega328P CPU frequency in Hz (16 MHz)
#endif

#ifndef NULL
#define NULL 0U
#endif

#include <stdint.h>
#include <util/twi.h>
#include <util/delay.h>

#include "atmega328p_i2c.h"

#define SHTC3_I2C_ADDRESS 0x70

#define SHTC3_SLEEP_COMMAND     0xB098
#define SHTC3_SLEEP_COMMAND_MSB 0xB0
#define SHTC3_SLEEP_COMMAND_LSB 0x98

#define SHTC3_WAKEUP_COMMAND     0x3517
#define SHTC3_WAKEUP_COMMAND_MSB 0x35
#define SHTC3_WAKEUP_COMMAND_LSB 0x17

#define SHTC3_MEASUREMENT_COMMAND_HIGH_RES_CLK_STRETCHING_TEMPERATURE_FIRST     0x7CA2
#define SHTC3_MEASUREMENT_COMMAND_HIGH_RES_CLK_STRETCHING_TEMPERATURE_FIRST_MSB 0x7C
#define SHTC3_MEASUREMENT_COMMAND_HIGH_RES_CLK_STRETCHING_TEMPERATURE_FIRST_LSB 0xA2

#define SHTC3_MEASUREMENT_COMMAND_HIGH_RES_CLK_STRETCHING_HUMIDITY_FIRST     0x5C24
#define SHTC3_MEASUREMENT_COMMAND_HIGH_RES_CLK_STRETCHING_HUMIDITY_FIRST_MSB 0x5C
#define SHTC3_MEASUREMENT_COMMAND_HIGH_RES_CLK_STRETCHING_HUMIDITY_FIRST_LSB 0x24

#define SHTC3_MEASUREMENT_COMMAND_HIGH_RES_TEMPERATURE_FIRST     0x7866
#define SHTC3_MEASUREMENT_COMMAND_HIGH_RES_TEMPERATURE_FIRST_MSB 0x78
#define SHTC3_MEASUREMENT_COMMAND_HIGH_RES_TEMPERATURE_FIRST_LSB 0x66

#define SHTC3_MEASUREMENT_COMMAND_HIGH_RES_HUMIDITY_FIRST     0x58E0
#define SHTC3_MEASUREMENT_COMMAND_HIGH_RES_HUMIDITY_FIRST_MSB 0x58
#define SHTC3_MEASUREMENT_COMMAND_HIGH_RES_HUMIDITY_FIRST_LSB 0xE0

#define SHTC3_MEASUREMENT_COMMAND_LOW_RES_CLK_STRETCHING_TEMPERATURE_FIRST     0x6458
#define SHTC3_MEASUREMENT_COMMAND_LOW_RES_CLK_STRETCHING_TEMPERATURE_FIRST_MSB 0x64
#define SHTC3_MEASUREMENT_COMMAND_LOW_RES_CLK_STRETCHING_TEMPERATURE_FIRST_LSB 0x58

#define SHTC3_MEASUREMENT_COMMAND_LOW_RES_CLK_STRETCHING_HUMIDITY_FIRST     0x44DE
#define SHTC3_MEASUREMENT_COMMAND_LOW_RES_CLK_STRETCHING_HUMIDITY_FIRST_MSB 0x44
#define SHTC3_MEASUREMENT_COMMAND_LOW_RES_CLK_STRETCHING_HUMIDITY_FIRST_LSB 0xDE

#define SHTC3_MEASUREMENT_COMMAND_LOW_RES_TEMPERATURE_FIRST     0x609C
#define SHTC3_MEASUREMENT_COMMAND_LOW_RES_TEMPERATURE_FIRST_MSB 0x60
#define SHTC3_MEASUREMENT_COMMAND_LOW_RES_TEMPERATURE_FIRST_LSB 0x9C

#define SHTC3_MEASUREMENT_COMMAND_LOW_RES_HUMIDITY_FIRST     0x401A
#define SHTC3_MEASUREMENT_COMMAND_LOW_RES_HUMIDITY_FIRST_MSB 0x40
#define SHTC3_MEASUREMENT_COMMAND_LOW_RES_HUMIDITY_FIRST_LSB 0x1A

#define SHTC3_POWERUP_TIME_MICROSECONDS           230U
#define SHTC3_MEASUREMENT_DURATION_MICROSECONDS 10800U

#define SHTC3_POWERUP_TIME_MILLISECONDS          1U
#define SHTC3_MEASUREMENT_DURATION_MILLISECONDS 11U

#define SHTC3_MEASUREMENT_BYTES_COUNT 6U
#define SHTC3_WRITE_BUFFER_COMMAND_BYTES_COUNT 2U

// SHTC3 return values
#define SHTC3_RET_OK 0



void shtc3_initialize(void);
int shtc3_get_temperature_and_humidity(float*, float*);

#endif /* SHTC3_H */
